language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: jOW957UIS7iDYOlQ1kGorFz2M54efuiJd71AfK2zeONZZE6/nJWkBThEzMKWeohUs+HDiMK3pbBksonc+TGLdn19j+2Cf5ar0V2sEalxVMcqX2xgf0d71kcyVNuPgMU5i4k6280cPXbfWamzHqfTL7B5U3y3nr39nstUd8Low8ByKkAo/40ZrrylXTww+r8NOveYLZHKvMouYeDTq8r4nFfTJbetY5eYwvjqBk94tmeBRzBDCYYGk+vpwGXFNY7oEsfofiVxfFa3Y7PNXGlcjwzihz4MuJTt6aIgCvknxyW3S4bJ/r3j+Skw87yNL4cpCiDmZn4DIyGEvvC/SdztzImjBujJZY8NRY7Mr/M2ah8XbV9iKitUlGc58ySkarkccyiYZ0HRc/O4OTrpn9LUcHID/LaDYDZhmuZqF17GmOMTpWEqgabiJ5PdGhoUn3P12KuJRciE2F0nhYbpvhe2S8TqcwvY+NzU3FAixoAI7PtoRCKolqbyi3M/MzVn2fXKNYpM+VnpWcKdUtgjXMcp7YfXnZZhz5hIdAXruEwKy0HUjwkb9WVlj8iWgAjFYq+QPXGQwvG8otJZwC+JTpN9N3+wvkXTQjQHdQAx1SGQPAqh+tw+wVDWxShD399633I/uAnRoa3Lr7NjcDaAzF1Jjbk8+slUjLh5NDAsLHAbmqg=
  app: nihao

