language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: ItgUadfrcfNaPiWBS+x5PWrVrNzVKhuyf/BFdP1jSnk7iDDuXDPQzddFNK1J7utCn+E6DVovyTCKoEBN0T1n0ZsHf35LfkXvDldKOSnzDxKx2LGGX/6pSe3bJMnuQOMH3+UVYbrZ75OKhFolL9syegyC7traPwyVDHgW6Ys3YG5ZxwYfA7UHs7hc4pMGukD4zYES+6gvE8TVfFjdk9ee1wwN4lCIldMGyuoa8eDauxX0CsvTDv+YyvhRgxSLDlR8atYsxs/ay7lghgdR1GkePDt7h4pyHs00kd2Xdd6MHeA9ZDikIL2sX9VZrz5ZKn43oW9T70tdezNYw7RXKUGWff/2NCJfu8h+oexS39NGuS+Jz5lOLtTYDB7Y54XyPl+GJc7pfFpH6PI6O8d4HM8QVw1xZDwCuimLimm5mmt9+eUZXbhP3d0kZv9Ew0YW5SHX5+58i1ebQVNrQojZtZRtc/8ScEgwanrNe69sHbwGKXj05UBrVw+s1358tJAMVzVyhJhr0smgmZ7klVkcnj0emEOqoqyccVdOqWZ79DmxIQij9uKcXTyBZ3VGAQxG3ZzJOAhJDJlFaAEhtnoeFKZUsY6GyN67SETtYy7fQamDMRM9qVCWyO8bUpCpuHyih3Dgc1y/FapBKCLoAxVdb7JyhvWLcNfvnWUM2zgKnHklK6o=
