language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: FVa4SIPBmWmVoxyK+Q2FeEL+5fHcYAfBX497M56yFalmchzkmBqKsY9/yiSIx06gQKu+6wFWFt9Cew4X6bkju5EjidOKG/YNjgBgNXQJk5c+oC5iTpsbtSAWLz9O/jUuaRZ8cJxc6E3mJoHivBadIx8hFwsPIQW4WTHey4joFV/ZN+gljKzerqlYKaC975I4iuxQxhQ8/qy9ozm+Ge162QnUJccH/AIXvv4SLkMNuaUESk0iZf6KLhbKf9TxROmzSxNkSV/AOYXUHvWa5aoJzy29AiUb3P3HGs54FNzMIgW2M5q7qEQKd2LNzcojmubxsm8988roTIG+NDCpPOCKVb4Gw6ucWTdR6dKqRAWymBrgiQcXme3vYKE0vu8fdvCIcOKJrE0DpFbJyOSGTUFUAinH8wE81UlVq863krDDlCzN5vaElx8HAFBC8qp2aM+hPSRlrkABWTRFZZEbP2tSISZT/JsqcgXJJ6id69fKvlUnh763jg9+bRlSGi4oA7NDnML4S55HBscQdrc1hVQc1XwCR7kiBVbLEjWZZ4v+7tZW01C4ZqcPznSw2wRuISloffQPvhhAC/m8RAnWlXaWOW61clJgVFDVzhM3uoZdIgTEce54ua+bTgppI4diKOEkfJYGjiULR0WmCb8uY2nMYXPuJYq+PtSja0jsD7JDpEQ=
