language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: J4EEoZOFzFwAJJB06rGJeP4XURhfFH2SGGGGMcYjtzvowhoFmlRWksZxpS7FFuy0hTm+VoVyuAcjFpzsMSFh59vFYF+A/GntM9U77EM6IBj3F+R1VnA9MhU5N5IKvtV4OCu4l71YjJ0Gjn662RcJ5k4x4MYHam+OLEpDrbw/osEOLz6PTobhqMwARIUWgRElbASx27WzIdNolCVZpki9+N6fknuK4Rko7b2vHyDDhNdg7p2445AIaeJUBkTHETl4S6rPySVqiqwjkm2wE5455j+khu+4I3qJ2iWmjDDWDQeKZi8dQ5d4MbXI4JjeyrA+ATEjsHPgAxAIquU4q9Vi/WsshOGPNKNisXVgDHVHM8cPjAup/yFenW0za3q49+VDsXBMQX8TxBz56vT6kdPNiK+1sT4PFFY7JAYcwd2uglMxWiloq145R/1m1/WJSBecFxoCMDUXuUZwBOfo6Ic3P9Y2edx2+sTQ0joaUgaJT+z1cMD2lxTfNT7WYIEZgcv9Zt+jkEsaQDiUTzlhl1cXtYaZhr0wN0HQuMdSuWPi2FEgQMh/420qov9zRefBEKbM2fbrZpIFWltPnxZuWUu9CLjrNgcv15f3DBNBGInFQUEoG+aNAiZWDUrP+SyVpHX6ICMeKuFZHdnUID8LnEnSvTWL4kQ3IdTYVJGnVd312fY=