language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: oDRf2upzmoya1S1BGFp4Kffq8wMfv20wOEZB4sN8zXsqe4gyQvZa9o0yCisD1KCQosvUKXkmj6FAed1JWXJQbF+RFniTYp2vx9EttmENYYvvdCi74IdE+niK5OmEwjFAmpeXtN2Utu+wukshp7OOTUV7Llgz8TEw8A5GWA/WIgeWEMrRTW0m+FLb/UKT/x8yEijKcdnnFnro/ANQO6A6X30YMjgBr6rW743trRkh2ro/oxERALguj3e1EAeRj9gl2gQLyFcTctGKZ7mlwaSV6vVlMpKidW0NXKIlWkvKHkb9/z3JA+Siscg/Ah0VZ01+1/Kt0ORfiB/6HGNin3iQ8ARUatNFTT1C3WedxZyZ+dXItizNQr/GnSzb/AGQlpNeQ5yS9Dq8ioyeUiZfaXMk9T920Cxpsk7AQLCCsA1tqkapd3EjKJ7YYXn3PhWWCJIU66CX4QKLq/CsFMfoBrJT0pbdo7wslw/sJGwq9G8sfWMo1B7ogyJNo3rst4+9mkq22dHXmG3RRg4kYY15hKb8yVDbSuYGcqGqgE3vWe8kyMX9MNlckfGjtSespQQZs8Wqjlz3PnyPlqjqJ1Qu4I/8DO+l0znHCrhX8zKk1GrxylOx8bHCK82xm5W1Jihak4OywqJWCR1BnZzi+TQfUlQ81Yo9wx8QTv+7Z0K4/VkP8L8=
