language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  api_key:
    secure: ox70RlivEvFQr9wB9FGs/kE7BZoNomjCkqxb/+3h7FQMW4teqvtdUsVmNOIZOFMjcOZHczZ654XM+70o40lVs58UhIQ9SaTtqyPmZ4LKQIVsuYs4aNXWlYnYfINcsHvtCpZvI3j3TROJRyBHorLzK7oVM6Q6E0bcuq0+lGfFwzuyrrd7sZ+x0efs/NVwgrtlQWgFMoIpIbqc6R2/Hl0GDUnb1YpLDolABjGXLrnGMr58OE6pJSQoHBecrURPna/2fMd0CLs/LV2v27ItnZ231uLqn1Uj14yppSQOmhUxCDn2HYHgLnDBBUGzqSrKtOJukAJSkBdvq8YU4nAO2miF5plC6NqIv6aKGkjsfiwHd8N5czPhFX7EayFCMEJfgy2gGDV/pTTIsFO7269hkB9Et80Q2qNrRBBfZwba3egborPSYf29Sqi1x5g4mR+m2wDdAK8dTx1UJpIQOYsE6GuvQl28BvgVToRJcrgWJ/jDK9Qphld7nnNjEFei9NbOw6jnghNCd6DQtmxcMV+BnxUEi7GOAaYTZbCu5qrMK3FeN/zGxRa6iBGVI5DNr0m7IvMni6SgRlRWOew07HsjJwCdLX9ttCMokkeSQmAIL764HNxx0CAsyhcJheMBNcAOoELNKArxlIU3MyQeIfiPgpWQbkA6rjwgau+FpvmC0TwY3Bo=
