language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: jw5PqxvhIrxhwetg9NFOz458dtJOPOdnd71n5FQpX5PmyH16sRWs/txz5LqorpmpHHiYdVJEQiqGkvYn/OIipX1Iuna5lSC32zRrCr12FsxDtsaHvMS3NTgsfrn1Zz99GQrwD0BC6YmwaSn3AsAFDU7/TOEBPqh4YYSCTaQO7/gMknK6byKJEkH17xe8GGWcRrHvwtvgAMY+IpBY1iplDO53EgmbJeq2VYHGKWeqafxOFMhxjGOjs9C5dtp9u3N09BhMErrYOVBHwXc/QO4swzEGmKQbT+tQvlOd4x9qmn1y6UXMMe3xfHk2lRVoR3X+HN7kaap721r6TQcs1SgC1zF1SA/o6TJ0XW7q6uRYvb5Ta9BdnqI+IVmWmhS6lgeuJng6qPFE07wLbCn5ioxqPKToGr9NiBqE/Uo6XTxEaGko/zGDFh8QlHN2BavR6QIXGTLpMfMiwA4Tb2/eUDmvUxtPlhi1yVz6laWlJXloImqFwwJABkHv1nu9ZLFUrJjvRScbksBIlm+73czkZON0U0vF+B6/In+UdwQ/kM23tey70JvPQRRRlm1Qyx9yqssF3/UHegrgX37o/rJ/8BPpbBuuwxsMf2gS2VbRj2+h74feuMoqpjv5C7bQMgZWWbPsUSTeT+sQhGZ/nvOKbHDlzUTkHXtTrfqRO+FQaP2UV+0=
