language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: m13b8A5Xix4Gz9JT4CT2k2Z6r5wSjPYMgNQT16v6DZpOrYUrpOt8wQgdB+55XNx8QzekKxEZSX96viG65W7LTgzY+nCcx4TzHoplLjrLGY/cmZ2XdDzmnATGNwWc7auID1gUyMvCGSUig80lVkMjx9oywlbFIAKAXifUJ61ffUeMQsACm/y3v9WK6fGJuAmYVH4V3+EHF33XEXEnl7tpxO2Wykz9ZWcMU//iL5fZ1NrXlJT5sUX/YolPzAJgSPnKAKvM6kijPFhUfvsupAry7Ue9DG7Pci0T3oTSFSt5JxvPLPP3w6WXndK6lewJV9kKGezTSNe9emzK9KT8ZCQaO9t9y+1m/Pnhbi0e4vlajvIhtGUlNJZ9GPdq++kp13RjSZidEeD4kWV6J8FRpKer4RxZjDNgAh1LeTVBns6vBopyaSp1RN+61epA0cKTwN2NsdGTXOhc29UXHt0jpdZg0LSHod9MY/UgxpNQRCfMqbkynspQXIPGkRZy4NZ1IvEMdsWCDBQLoXzu5z48SwIHkU+TCOppsW0esAiZ94NFA0VjERnNE4MvvjiorForuA/nWFFtROwsdMod7kaQiXsB5ZzGVRkOJPCRMvBP1prGR7UgeOJdWeNUtR+3kE+u+6n7bqWjOjr2K4ktZphk1LIwpH5d/cRXQ6eltO7T2OZr7vI=