language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  api_key:
    secure: hm5XK4jhdiJwW3qaujikrSQBdQru97U3I492u7DXZkvLYyQdd2sp4Hd6PM4ptoNXffss0kOCm+H5DWv25aw7Af/KHB4XbxgIXcBWTxFxscf0eko9MItP+pWPshbum5d+ZT4qYi0mFNPSFzR1XdFz/0xPrSooc7/gill9h+DnX886vXFmU8QxNhDZ75A6BVTPCiYDXOm4WTwUhOnN3hEWS4XXtzJeLYFlIVesJUONqzPVX2VXwr5GB2/798qQ6XkInvTUcICeKz4S/8ZnNMrdNj+6pQ3yCaBAurX+8BVj/jLBDaqxAIEuSN2IuIayVX7eRpGSMwktU1g2NlCr7tpGWlxUUl091rayBkIORl5Kz7vKYRZgh8VtYjw5TCjk+73oCymy4v3XfdBPNNo5WiWZm3BoOvB7oQnlU2iE7xS44bnKjNiRDGZJ1P7tjxq33pKu5mVRqLO1st/F6eyZT9O1n9zApEC4ZPijglCOztjhuIPORaLZP92IJq8zrZI4xXgnn+T36zG56X4GcCflTjAlgpsFT/IKmlrXODraL82NCs/BY7/OTC6X6M4X+8nF6+ZGykprUyGilQu/XYPQhtCktN3EL/03NVHDUpLIPi3K45sFSFcrhhcPKNJTvDZOJI0/bfEwo8jv0wG+o5Sg+zGjFK8ay3QOR1bO3l0XAAnWli0=
